Map<String, dynamic> buildPostBoostRequestPayload({
  required String postId,
  required String userId,
  required String packageType,
  required String packageTitle,
  required String description,
  required double price,
  required int days,
  required int reach,
  required String postContent,
  required String postAuthorName,
  required String postAuthorId,
  String? postImage,
  required String objectiveId,
  required String objectiveTitle,
}) {
  return {
    'postId': postId,
    'userId': userId,
    'packageType': packageType,
    'packageTitle': packageTitle,
    'description': description,
    'price': price,
    'days': days,
    'reach': reach,
    'status': 'pending_approval',
    'createdAt': null,
    'postContent': postContent,
    'postAuthorName': postAuthorName,
    'postAuthorId': postAuthorId,
    'objectiveId': objectiveId,
    'objectiveTitle': objectiveTitle,
    if (postImage != null && postImage.isNotEmpty) 'postImage': postImage,
  };
}
