import '../../models/fertilizer/fertilizer_crop.dart';
import '../../models/fertilizer/fertilizer_location.dart';
import '../../models/fertilizer/fertilizer_product.dart';
import '../../models/fertilizer/fertilizer_recommendation.dart';
import '../../models/fertilizer/fertilizer_source.dart';

class FertilizerSeedData {
  // ---------------------------------------------------------------------------
  // 1. COUNTRIES & REGIONS
  // ---------------------------------------------------------------------------
  static const List<FertilizerCountry> countries = [
    FertilizerCountry(
      code: 'ZW',
      name: 'Zimbabwe',
      flagEmoji: '🇿🇼',
      defaultAreaUnit: 'Hectares',
      defaultBagSizeKg: 50.0,
      regions: [
        'Natural Region I (High Rainfall / Eastern Highlands)',
        'Natural Region II (Intensive Farming / Mashonaland)',
        'Natural Region III (Semi-Intensive / Midlands)',
        'Natural Region IV (Semi-Extensive / Lowveld)',
        'Natural Region V (Extensive / Arid)',
        'Harare Metropolitan',
        'Bulawayo Metropolitan',
        'Manicaland',
        'Mashonaland Central',
        'Mashonaland East',
        'Mashonaland West',
        'Masvingo',
        'Matabeleland North',
        'Matabeleland South',
        'Midlands',
      ],
    ),
    FertilizerCountry(
      code: 'KE',
      name: 'Kenya',
      flagEmoji: '🇰🇪',
      defaultAreaUnit: 'Acres',
      defaultBagSizeKg: 50.0,
      regions: [
        'Rift Valley (Trans-Nzoia, Uasin Gishu, Nakuru)',
        'Western (Kakamega, Bungoma, Busia)',
        'Central Highlands (Kiambu, Nyeri, Muranga, Meru)',
        'Eastern (Machakos, Makueni, Embu)',
        'Nyanza (Kisii, Kisumu, Homa Bay)',
        'Coast Region (Kilifi, Kwale, Taita-Taveta)',
      ],
    ),
    FertilizerCountry(
      code: 'ZA',
      name: 'South Africa',
      flagEmoji: '🇿🇦',
      defaultAreaUnit: 'Hectares',
      defaultBagSizeKg: 50.0,
      regions: [
        'Highveld (Gauteng / East Mpumalanga)',
        'Free State (Grain Belt)',
        'Mpumalanga',
        'Limpopo (Subtropical & Bushveld)',
        'KwaZulu-Natal',
        'Western Cape (Winter Rainfall)',
        'Eastern Cape',
        'North West',
        'Northern Cape',
      ],
    ),
    FertilizerCountry(
      code: 'BR',
      name: 'Brazil',
      flagEmoji: '🇧🇷',
      defaultAreaUnit: 'Hectares',
      defaultBagSizeKg: 50.0,
      regions: [
        'Centro-Oeste / Cerrado (Mato Grosso, Goiás, MS)',
        'Sul (Paraná, Rio Grande do Sul, Santa Catarina)',
        'Sudeste (São Paulo, Minas Gerais, Espírito Santo)',
        'Nordeste / Matopiba (Bahia, Maranhão, Piauí, Tocantins)',
        'Norte (Pará, Rondônia)',
      ],
    ),
    FertilizerCountry(
      code: 'NG',
      name: 'Nigeria',
      flagEmoji: '🇳🇬',
      defaultAreaUnit: 'Hectares',
      defaultBagSizeKg: 50.0,
      regions: [
        'North Central (Benue, Niger, Plateau, Kaduna)',
        'North West (Kano, Katsina, Sokoto, Zamfara)',
        'North East (Borno, Adamawa, Bauchi, Taraba)',
        'South West (Oyo, Ogun, Osun, Ondo, Ekiti, Lagos)',
        'South East (Enugu, Anambra, Imo, Abia, Ebonyi)',
        'South South (Delta, Edo, Rivers, Cross River)',
      ],
    ),
    FertilizerCountry(
      code: 'ZM',
      name: 'Zambia',
      flagEmoji: '🇿🇲',
      defaultAreaUnit: 'Hectares',
      defaultBagSizeKg: 50.0,
      regions: [
        'Region I (Southern & Western Valleys - Low Rainfall)',
        'Region IIa (Central, Eastern, Lusaka Plateaus - Medium)',
        'Region IIb (Kalahari Sands - Western Province)',
        'Region III (Northern, Luapula, Copperbelt, North-Western - High)',
      ],
    ),
    FertilizerCountry(
      code: 'GH',
      name: 'Ghana',
      flagEmoji: '🇬🇭',
      defaultAreaUnit: 'Acres',
      defaultBagSizeKg: 50.0,
      regions: [
        'Forest Zone (Ashanti, Eastern, Western, Central)',
        'Transitional Zone (Bono, Bono East, Ahafo)',
        'Guinea Savanna (Northern, Savannah, North East)',
        'Sudan Savanna (Upper East, Upper West)',
        'Coastal Savanna (Greater Accra, Central, Volta)',
      ],
    ),
    FertilizerCountry(
      code: 'TZ',
      name: 'Tanzania',
      flagEmoji: '🇹🇿',
      defaultAreaUnit: 'Acres',
      defaultBagSizeKg: 50.0,
      regions: [
        'Southern Highlands (Mbeya, Iringa, Ruvuma, Njombe, Rukwa)',
        'Northern Zone (Arusha, Kilimanjaro, Manyara)',
        'Lake Zone (Mwanza, Mara, Kagera, Shinyanga)',
        'Central Zone (Dodoma, Singida)',
        'Coastal Zone (Dar es Salaam, Tanga, Pwani, Morogoro)',
      ],
    ),
    FertilizerCountry(
      code: 'ET',
      name: 'Ethiopia',
      flagEmoji: '🇪🇹',
      defaultAreaUnit: 'Hectares',
      defaultBagSizeKg: 50.0,
      regions: [
        'Oromia Highlands',
        'Amhara Region',
        'SNNPR (Southern Nations)',
        'Sidama',
        'Tigray',
        'Rift Valley Lowlands',
      ],
    ),
    FertilizerCountry(
      code: 'UG',
      name: 'Uganda',
      flagEmoji: '🇺🇬',
      defaultAreaUnit: 'Acres',
      defaultBagSizeKg: 50.0,
      regions: [
        'Central Region (Buganda / Lake Victoria Basin)',
        'Western Region (Ankole, Kigezi, Bunyoro, Tooro)',
        'Eastern Region (Busoga, Bugisu, Teso)',
        'Northern Region (Acholi, Lango, West Nile)',
      ],
    ),
    FertilizerCountry(
      code: 'US',
      name: 'United States',
      flagEmoji: '🇺🇸',
      defaultAreaUnit: 'Acres',
      defaultBagSizeKg: 22.68, // 50 lbs
      regions: [
        'Corn Belt / Midwest (Iowa, Illinois, Indiana, Ohio, Minnesota)',
        'Great Plains (Kansas, Nebraska, South Dakota, North Dakota)',
        'Southeast (Georgia, North Carolina, Florida, Alabama)',
        'Delta Region (Mississippi, Arkansas, Louisiana)',
        'California Central Valley & West Coast',
        'Northeast & Mid-Atlantic',
      ],
    ),
    FertilizerCountry(
      code: 'IN',
      name: 'India',
      flagEmoji: '🇮🇳',
      defaultAreaUnit: 'Acres',
      defaultBagSizeKg: 45.0, // Indian standard neem coated urea is 45kg bag
      regions: [
        'Indo-Gangetic Plains (Punjab, Haryana, Uttar Pradesh, Bihar)',
        'Deccan Plateau (Maharashtra, Karnataka, Telangana)',
        'Western Coastal & Gujarat',
        'Eastern Coastal & West Bengal / Odisha',
        'Southern Zone (Tamil Nadu, Andhra Pradesh, Kerala)',
        'Central Zone (Madhya Pradesh, Chhattisgarh)',
      ],
    ),
  ];

  // ---------------------------------------------------------------------------
  // 2. AUTHORITATIVE AGRONOMIC SOURCES
  // ---------------------------------------------------------------------------
  static const List<FertilizerSource> sources = [
    FertilizerSource(
      id: 'src_fao_nutrition',
      organization: 'FAO (Food and Agriculture Organization of the UN)',
      title: 'Plant Nutrition for Food Security: A Guide for Integrated Nutrient Management',
      country: 'Global',
      year: 2023,
      url: 'https://www.fao.org/land-water/databases-and-software/crop-information',
      notes: 'Global FAO benchmark nutrient requirements and soil fertility guidelines.',
      isVerified: true,
    ),
    FertilizerSource(
      id: 'src_drss_zim',
      organization: 'DR&SS (Department of Research & Specialist Services)',
      title: 'Fertilizer Recommendation Handbook for Field and Horticultural Crops',
      country: 'Zimbabwe',
      year: 2022,
      url: 'http://www.drss.gov.zw',
      notes: 'Zimbabwe Ministry of Lands, Agriculture, Fisheries, Water and Rural Development authoritative crop advisory.',
      isVerified: true,
    ),
    FertilizerSource(
      id: 'src_embrapa_br',
      organization: 'EMBRAPA (Empresa Brasileira de Pesquisa Agropecuária)',
      title: 'Manual de Adubação e Calagem para os Estados do Brasil (Cerrado & Grãos)',
      country: 'Brazil',
      year: 2024,
      url: 'https://www.embrapa.br',
      notes: 'Embrapa Cerrados / Embrapa Milho e Sorgo official soil fertility and fertilizer recommendations.',
      isVerified: true,
    ),
    FertilizerSource(
      id: 'src_kalro_ke',
      organization: 'KALRO (Kenya Agricultural & Livestock Research Organization)',
      title: 'Site-Specific Nutrient Management and Fertilizer Use Manual for Kenya',
      country: 'Kenya',
      year: 2023,
      url: 'https://www.kalro.org',
      notes: 'Kenya Ministry of Agriculture and KALRO crop nutrient guidelines.',
      isVerified: true,
    ),
    FertilizerSource(
      id: 'src_arc_za',
      organization: 'ARC (Agricultural Research Council of South Africa)',
      title: 'Fertilizer Guide for Summer Grains and Vegetable Production',
      country: 'South Africa',
      year: 2023,
      url: 'https://www.arc.agric.za',
      notes: 'Fertilizer Society of South Africa (Fertasa) & ARC agronomic recommendations.',
      isVerified: true,
    ),
    FertilizerSource(
      id: 'src_usda_extension',
      organization: 'USDA-NIFA / Land-Grant University Extension (Iowa State & Purdue)',
      title: 'Nutrient Management for Field Crops and Vegetables: Tri-State Fertilizer Guide',
      country: 'United States',
      year: 2023,
      url: 'https://extension.purdue.edu',
      notes: 'Midwest and Tri-State university soil fertility and fertilizer recommendations.',
      isVerified: true,
    ),
    FertilizerSource(
      id: 'src_icar_india',
      organization: 'ICAR (Indian Council of Agricultural Research)',
      title: 'Soil Test Based Fertilizer Recommendations for Targeted Yields',
      country: 'India',
      year: 2023,
      url: 'https://icar.org.in',
      notes: 'ICAR All India Coordinated Research Project on Soil Test Crop Response (STCR).',
      isVerified: true,
    ),
    FertilizerSource(
      id: 'src_iita_west_africa',
      organization: 'IITA (International Institute of Tropical Agriculture)',
      title: 'Good Agricultural Practices: Nutrient Management in West African Savannas',
      country: 'Nigeria',
      year: 2023,
      url: 'https://www.iita.org',
      notes: 'IITA & Federal Ministry of Agriculture and Rural Development guidelines.',
      isVerified: true,
    ),
  ];

  // ---------------------------------------------------------------------------
  // 3. FERTILIZER PRODUCTS (LOCAL & INTERNATIONAL)
  // ---------------------------------------------------------------------------
  static const List<FertilizerProduct> products = [
    // Standard Global Straights
    FertilizerProduct(
      id: 'prod_urea_global',
      name: 'Urea',
      manufacturer: 'Standard Commodity',
      countryCode: 'GLOBAL',
      countryName: 'Global',
      nPercent: 46.0,
      pPercent: 0.0,
      kPercent: 0.0,
      physicalForm: FertilizerForm.prilled,
      packageSize: 50.0,
      packageUnit: 'kg',
      usageNotes: 'High-nitrogen top dressing. Incorporate or apply before rain/irrigation to avoid ammonia volatilization.',
    ),
    FertilizerProduct(
      id: 'prod_dap_global',
      name: 'DAP (Diammonium Phosphate 18-46-0)',
      manufacturer: 'Standard Commodity',
      countryCode: 'GLOBAL',
      countryName: 'Global',
      nPercent: 18.0,
      pPercent: 46.0,
      kPercent: 0.0,
      physicalForm: FertilizerForm.granular,
      packageSize: 50.0,
      packageUnit: 'kg',
      usageNotes: 'Excellent high-phosphate basal planting fertilizer for vigorous root establishment.',
    ),
    FertilizerProduct(
      id: 'prod_map_global',
      name: 'MAP (Monoammonium Phosphate 11-52-0)',
      manufacturer: 'Standard Commodity',
      countryCode: 'GLOBAL',
      countryName: 'Global',
      nPercent: 11.0,
      pPercent: 52.0,
      kPercent: 0.0,
      physicalForm: FertilizerForm.granular,
      packageSize: 50.0,
      packageUnit: 'kg',
      usageNotes: 'High-purity phosphorus source; safer in calcareous soils than DAP.',
    ),
    FertilizerProduct(
      id: 'prod_can_global',
      name: 'CAN (Calcium Ammonium Nitrate 27-0-0 + 8Ca)',
      manufacturer: 'Standard Commodity',
      countryCode: 'GLOBAL',
      countryName: 'Global',
      nPercent: 27.0,
      pPercent: 0.0,
      kPercent: 0.0,
      caPercent: 8.0,
      physicalForm: FertilizerForm.granular,
      packageSize: 50.0,
      packageUnit: 'kg',
      usageNotes: 'Neutral-reacting nitrogen with essential calcium; prevents soil acidification.',
    ),
    FertilizerProduct(
      id: 'prod_mop_global',
      name: 'MOP / Potassium Chloride (0-0-60)',
      manufacturer: 'Standard Commodity',
      countryCode: 'GLOBAL',
      countryName: 'Global',
      nPercent: 0.0,
      pPercent: 0.0,
      kPercent: 60.0,
      physicalForm: FertilizerForm.granular,
      packageSize: 50.0,
      packageUnit: 'kg',
      usageNotes: 'High-potash source for stalk strength, drought tolerance, and grain filling.',
    ),
    FertilizerProduct(
      id: 'prod_sop_global',
      name: 'SOP / Potassium Sulphate (0-0-50 + 18S)',
      manufacturer: 'Standard Commodity',
      countryCode: 'GLOBAL',
      countryName: 'Global',
      nPercent: 0.0,
      pPercent: 0.0,
      kPercent: 50.0,
      sPercent: 18.0,
      physicalForm: FertilizerForm.granular,
      packageSize: 50.0,
      packageUnit: 'kg',
      usageNotes: 'Chloride-free potassium and sulfur; ideal for sensitive crops like tobacco, potatoes, and berries.',
    ),
    FertilizerProduct(
      id: 'prod_npk_17_17_17',
      name: 'NPK 17-17-17 Balanced Compound',
      manufacturer: 'Standard Commodity',
      countryCode: 'GLOBAL',
      countryName: 'Global',
      nPercent: 17.0,
      pPercent: 17.0,
      kPercent: 17.0,
      physicalForm: FertilizerForm.granular,
      packageSize: 50.0,
      packageUnit: 'kg',
      usageNotes: 'Evenly balanced all-purpose basal and maintenance fertilizer.',
    ),
    FertilizerProduct(
      id: 'prod_npk_15_15_15',
      name: 'NPK 15-15-15 Compound',
      manufacturer: 'Standard Commodity',
      countryCode: 'GLOBAL',
      countryName: 'Global',
      nPercent: 15.0,
      pPercent: 15.0,
      kPercent: 15.0,
      physicalForm: FertilizerForm.granular,
      packageSize: 50.0,
      packageUnit: 'kg',
      usageNotes: 'Widely used balanced basal fertilizer.',
    ),

    // Zimbabwe Specific Products
    FertilizerProduct(
      id: 'prod_zw_compound_d',
      name: 'Compound D (7-14-7 + 6S)',
      manufacturer: 'Windmill / ZFC / FSG',
      countryCode: 'ZW',
      countryName: 'Zimbabwe',
      nPercent: 7.0,
      pPercent: 14.0,
      kPercent: 7.0,
      sPercent: 6.0,
      physicalForm: FertilizerForm.granular,
      packageSize: 50.0,
      packageUnit: 'kg',
      usageNotes: 'Standard basal fertilizer for maize, sorghum, and small grains in Zimbabwe sandy and loam soils.',
    ),
    FertilizerProduct(
      id: 'prod_zw_compound_c',
      name: 'Compound C (6-15-12 + 6S)',
      manufacturer: 'Windmill / ZFC',
      countryCode: 'ZW',
      countryName: 'Zimbabwe',
      nPercent: 6.0,
      pPercent: 15.0,
      kPercent: 12.0,
      sPercent: 6.0,
      physicalForm: FertilizerForm.granular,
      packageSize: 50.0,
      packageUnit: 'kg',
      usageNotes: 'High-potash basal fertilizer for horticultural crops, potatoes, tomatoes, and tobacco seedbeds.',
    ),
    FertilizerProduct(
      id: 'prod_zw_compound_s',
      name: 'Compound S (7-21-7 + 9S)',
      manufacturer: 'Windmill / ZFC',
      countryCode: 'ZW',
      countryName: 'Zimbabwe',
      nPercent: 7.0,
      pPercent: 21.0,
      kPercent: 7.0,
      sPercent: 9.0,
      physicalForm: FertilizerForm.granular,
      packageSize: 50.0,
      packageUnit: 'kg',
      usageNotes: 'High-phosphate, high-sulfur basal fertilizer designed for soybeans, groundnuts, and legumes.',
    ),
    FertilizerProduct(
      id: 'prod_zw_compound_j',
      name: 'Compound J (15-5-20 + 4S)',
      manufacturer: 'Windmill / ZFC',
      countryCode: 'ZW',
      countryName: 'Zimbabwe',
      nPercent: 15.0,
      pPercent: 5.0,
      kPercent: 20.0,
      sPercent: 4.0,
      physicalForm: FertilizerForm.granular,
      packageSize: 50.0,
      packageUnit: 'kg',
      usageNotes: 'High-nitrogen and high-potash top dress formulation for bananas, sugarcane, and fruit trees.',
    ),
    FertilizerProduct(
      id: 'prod_zw_an',
      name: 'Ammonium Nitrate (34.5% N)',
      manufacturer: 'Sable Chemicals / ZFC / Windmill',
      countryCode: 'ZW',
      countryName: 'Zimbabwe',
      nPercent: 34.5,
      pPercent: 0.0,
      kPercent: 0.0,
      physicalForm: FertilizerForm.prilled,
      packageSize: 50.0,
      packageUnit: 'kg',
      usageNotes: 'Standard quick-acting top dressing in Zimbabwe. Contains both nitrate (rapid) and ammonium (sustained) nitrogen.',
    ),

    // Brazil Specific Products
    FertilizerProduct(
      id: 'prod_br_npk_04_14_08',
      name: 'NPK 04-14-08 (Adubo Plantio Cerrado)',
      manufacturer: 'Yara Brasil / Mosaic / Heringer',
      countryCode: 'BR',
      countryName: 'Brazil',
      nPercent: 4.0,
      pPercent: 14.0,
      kPercent: 8.0,
      physicalForm: FertilizerForm.granular,
      packageSize: 50.0,
      packageUnit: 'kg',
      usageNotes: 'Formulação clássica de plantio para solos tropicais com necessidade de fósforo.',
    ),
    FertilizerProduct(
      id: 'prod_br_npk_05_25_15',
      name: 'NPK 05-25-15 (Plantio Grãos Alto Rendimento)',
      manufacturer: 'Yara Brasil / Fertipar',
      countryCode: 'BR',
      countryName: 'Brazil',
      nPercent: 5.0,
      pPercent: 25.0,
      kPercent: 15.0,
      sPercent: 5.0,
      physicalForm: FertilizerForm.granular,
      packageSize: 50.0,
      packageUnit: 'kg',
      usageNotes: 'Adubo de alta concentração fosfatada para soja e milho no Cerrado.',
    ),
    FertilizerProduct(
      id: 'prod_br_npk_20_00_20',
      name: 'NPK 20-00-20 (Adubo Cobertura)',
      manufacturer: 'Yara Brasil / Mosaic',
      countryCode: 'BR',
      countryName: 'Brazil',
      nPercent: 20.0,
      pPercent: 0.0,
      kPercent: 20.0,
      physicalForm: FertilizerForm.granular,
      packageSize: 50.0,
      packageUnit: 'kg',
      usageNotes: 'Adubo de cobertura equilibrado NK para milho, cana-de-açúcar e café.',
    ),
    FertilizerProduct(
      id: 'prod_br_ureia',
      name: 'Ureia Agrícola Granulada (45% N)',
      manufacturer: 'Petrobras / Fertilizantes Nacionais',
      countryCode: 'BR',
      countryName: 'Brazil',
      nPercent: 45.0,
      pPercent: 0.0,
      kPercent: 0.0,
      physicalForm: FertilizerForm.granular,
      packageSize: 50.0,
      packageUnit: 'kg',
      usageNotes: 'Fonte de nitrogênio mais utilizada no Brasil para adubação de cobertura.',
    ),

    // Kenya Specific Products
    FertilizerProduct(
      id: 'prod_ke_mavuno_planting',
      name: 'Mavuno Planting NPK (10-26-10 + Micros)',
      manufacturer: 'Athiriver Mining / Yara Kenya',
      countryCode: 'KE',
      countryName: 'Kenya',
      nPercent: 10.0,
      pPercent: 26.0,
      kPercent: 10.0,
      sPercent: 4.0,
      caPercent: 8.0,
      micronutrients: {'Zn': 0.5, 'B': 0.2},
      physicalForm: FertilizerForm.granular,
      packageSize: 50.0,
      packageUnit: 'kg',
      usageNotes: 'Enriched planting fertilizer with sulfur, calcium, zinc, and boron tailored for Kenyan soils.',
    ),
    FertilizerProduct(
      id: 'prod_ke_mavuno_topdress',
      name: 'Mavuno Topdress (26-0-0 + Micros)',
      manufacturer: 'Athiriver Mining',
      countryCode: 'KE',
      countryName: 'Kenya',
      nPercent: 26.0,
      pPercent: 0.0,
      kPercent: 0.0,
      caPercent: 10.0,
      physicalForm: FertilizerForm.granular,
      packageSize: 50.0,
      packageUnit: 'kg',
      usageNotes: 'Top dressing enriched with calcium to prevent soil acidification in Western & Rift Valley Kenya.',
    ),
    FertilizerProduct(
      id: 'prod_ke_npk_23_23_0',
      name: 'NPK 23-23-0 (Cereal Planting)',
      manufacturer: 'MEA Fertilizers / KTDA',
      countryCode: 'KE',
      countryName: 'Kenya',
      nPercent: 23.0,
      pPercent: 23.0,
      kPercent: 0.0,
      physicalForm: FertilizerForm.granular,
      packageSize: 50.0,
      packageUnit: 'kg',
      usageNotes: 'High-nitrogen & phosphorus planting blend used in Rift Valley cereal systems.',
    ),

    // South Africa Specific Products
    FertilizerProduct(
      id: 'prod_za_3_2_1_25',
      name: '3:2:1 (25) + 0.5% Zn (Highveld Basal)',
      manufacturer: 'Sasol / Omnia / Kynoch',
      countryCode: 'ZA',
      countryName: 'South Africa',
      nPercent: 12.5,
      pPercent: 8.3,
      kPercent: 4.2,
      micronutrients: {'Zn': 0.5},
      physicalForm: FertilizerForm.granular,
      packageSize: 50.0,
      packageUnit: 'kg',
      usageNotes: 'South African standard grain basal fertilizer with zinc.',
    ),
    FertilizerProduct(
      id: 'prod_za_2_3_4_30',
      name: '2:3:4 (30) + 0.5% Zn (Vegetable & Potato Basal)',
      manufacturer: 'Omnia / Kynoch',
      countryCode: 'ZA',
      countryName: 'South Africa',
      nPercent: 6.7,
      pPercent: 10.0,
      kPercent: 13.3,
      micronutrients: {'Zn': 0.5},
      physicalForm: FertilizerForm.granular,
      packageSize: 50.0,
      packageUnit: 'kg',
      usageNotes: 'High-potash basal blend for vegetables, potatoes, and sandy soils.',
    ),
    FertilizerProduct(
      id: 'prod_za_lan_28',
      name: 'LAN 28% N (Limestone Ammonium Nitrate)',
      manufacturer: 'Sasol / Omnia',
      countryCode: 'ZA',
      countryName: 'South Africa',
      nPercent: 28.0,
      pPercent: 0.0,
      kPercent: 0.0,
      caPercent: 4.0,
      physicalForm: FertilizerForm.granular,
      packageSize: 50.0,
      packageUnit: 'kg',
      usageNotes: 'South Africa standard safe top dressing; minimal volatilization risk.',
    ),

    // United States Products
    FertilizerProduct(
      id: 'prod_us_10_10_10',
      name: 'All-Purpose Garden NPK 10-10-10',
      manufacturer: 'Scotts / Southern States',
      countryCode: 'US',
      countryName: 'United States',
      nPercent: 10.0,
      pPercent: 10.0,
      kPercent: 10.0,
      physicalForm: FertilizerForm.granular,
      packageSize: 22.68, // 50 lbs
      packageUnit: 'kg',
      usageNotes: 'Balanced general application for home gardens and small farms in the US.',
    ),
    FertilizerProduct(
      id: 'prod_us_uan_32',
      name: 'UAN 32% (Urea Ammonium Nitrate Liquid)',
      manufacturer: 'Nutrien / CF Industries',
      countryCode: 'US',
      countryName: 'United States',
      nPercent: 32.0,
      pPercent: 0.0,
      kPercent: 0.0,
      physicalForm: FertilizerForm.liquid,
      packageSize: 20.0,
      packageUnit: 'L',
      usageNotes: 'Liquid nitrogen solution for precision injection, side-dress, or pivot fertigation.',
    ),

    // India Specific Products
    FertilizerProduct(
      id: 'prod_in_neem_urea',
      name: 'Neem-Coated Urea (46% N)',
      manufacturer: 'IFFCO / KRIBHCO / NFL',
      countryCode: 'IN',
      countryName: 'India',
      nPercent: 46.0,
      pPercent: 0.0,
      kPercent: 0.0,
      physicalForm: FertilizerForm.prilled,
      packageSize: 45.0, // Indian standard bag
      packageUnit: 'kg',
      usageNotes: 'Neem coating slows nitrogen release and enhances nitrogen use efficiency.',
    ),
    FertilizerProduct(
      id: 'prod_in_npk_10_26_26',
      name: 'IFFCO NPK 10-26-26 Complex',
      manufacturer: 'IFFCO',
      countryCode: 'IN',
      countryName: 'India',
      nPercent: 10.0,
      pPercent: 26.0,
      kPercent: 26.0,
      physicalForm: FertilizerForm.granular,
      packageSize: 50.0,
      packageUnit: 'kg',
      usageNotes: 'High-phosphorus and high-potassium complex fertilizer for sugarcane, potato, and oilseeds.',
    ),
  ];

  // ---------------------------------------------------------------------------
  // 4. CROPS (LARGE EXPANDABLE DATABASE ACROSS CATEGORIES)
  // ---------------------------------------------------------------------------
  static const List<FertilizerCrop> crops = [
    // FIELD CROPS
    FertilizerCrop(
      id: 'crop_maize',
      name: 'Maize (Corn)',
      scientificName: 'Zea mays',
      category: CropCategory.fieldCrop,
      iconEmoji: '🌽',
      defaultStages: [
        'Basal / Planting',
        'Early Vegetative (V4 - V6 / Knee High)',
        'Second Top Dress (V10 - Tasseling)',
        'All Season Total',
      ],
      supportedProductionSystems: ['Rain-fed', 'Irrigated'],
      requiresYieldTarget: true,
      defaultYieldTarget: 5.0,
      yieldUnit: 'tonnes/ha',
    ),
    FertilizerCrop(
      id: 'crop_sorghum',
      name: 'Sorghum',
      scientificName: 'Sorghum bicolor',
      category: CropCategory.fieldCrop,
      iconEmoji: '🌾',
      defaultStages: [
        'Basal / Planting',
        'Top Dressing (3-4 Weeks after emergence)',
        'All Season Total',
      ],
      supportedProductionSystems: ['Rain-fed', 'Irrigated'],
      requiresYieldTarget: true,
      defaultYieldTarget: 3.0,
      yieldUnit: 'tonnes/ha',
    ),
    FertilizerCrop(
      id: 'crop_pearl_millet',
      name: 'Pearl Millet',
      scientificName: 'Pennisetum glaucum',
      category: CropCategory.fieldCrop,
      iconEmoji: '🌾',
      defaultStages: [
        'Basal / Planting',
        'Top Dressing (Tillering stage)',
        'All Season Total',
      ],
      supportedProductionSystems: ['Rain-fed'],
      requiresYieldTarget: false,
    ),
    FertilizerCrop(
      id: 'crop_wheat',
      name: 'Wheat',
      scientificName: 'Triticum aestivum',
      category: CropCategory.fieldCrop,
      iconEmoji: '🌾',
      defaultStages: [
        'Basal / Planting',
        'Crown Root Initiation (CRI / Tillering)',
        'Booting / Heading Stage',
        'All Season Total',
      ],
      supportedProductionSystems: ['Irrigated', 'Rain-fed'],
      requiresYieldTarget: true,
      defaultYieldTarget: 6.0,
      yieldUnit: 'tonnes/ha',
    ),
    FertilizerCrop(
      id: 'crop_barley',
      name: 'Barley',
      scientificName: 'Hordeum vulgare',
      category: CropCategory.fieldCrop,
      iconEmoji: '🌾',
      defaultStages: ['Basal / Planting', 'Tillering Top Dress', 'All Season Total'],
      supportedProductionSystems: ['Irrigated', 'Rain-fed'],
    ),
    FertilizerCrop(
      id: 'crop_rice',
      name: 'Rice (Paddy / Lowland & Upland)',
      scientificName: 'Oryza sativa',
      category: CropCategory.fieldCrop,
      iconEmoji: '🍚',
      defaultStages: [
        'Basal / Transplanting',
        'Active Tillering (2-3 Weeks)',
        'Panicle Initiation',
        'All Season Total',
      ],
      supportedProductionSystems: ['Flooded / Irrigated', 'Upland Rain-fed'],
      requiresYieldTarget: true,
      defaultYieldTarget: 6.0,
      yieldUnit: 'tonnes/ha',
    ),
    FertilizerCrop(
      id: 'crop_soybean',
      name: 'Soybean',
      scientificName: 'Glycine max',
      category: CropCategory.fieldCrop,
      iconEmoji: '🫘',
      defaultStages: ['Basal / Planting', 'Pod Inoculation & Bloom', 'All Season Total'],
      supportedProductionSystems: ['Rain-fed', 'Irrigated'],
      requiresYieldTarget: true,
      defaultYieldTarget: 3.0,
      yieldUnit: 'tonnes/ha',
    ),
    FertilizerCrop(
      id: 'crop_groundnut',
      name: 'Groundnuts (Peanuts)',
      scientificName: 'Arachis hypogaea',
      category: CropCategory.fieldCrop,
      iconEmoji: '🥜',
      defaultStages: ['Basal / Planting', 'Pegging / Gypsum Application', 'All Season Total'],
      supportedProductionSystems: ['Rain-fed', 'Irrigated'],
      requiresYieldTarget: false,
    ),
    FertilizerCrop(
      id: 'crop_cotton',
      name: 'Cotton',
      scientificName: 'Gossypium hirsutum',
      category: CropCategory.fieldCrop,
      iconEmoji: '🌱',
      defaultStages: ['Basal / Planting', 'Square Formation', 'Peak Flowering & Boll Set', 'All Season Total'],
      supportedProductionSystems: ['Rain-fed', 'Irrigated'],
    ),
    FertilizerCrop(
      id: 'crop_sunflower',
      name: 'Sunflower',
      scientificName: 'Helianthus annuus',
      category: CropCategory.fieldCrop,
      iconEmoji: '🌻',
      defaultStages: ['Basal / Planting', 'Button / Bud Stage Top Dress', 'All Season Total'],
      supportedProductionSystems: ['Rain-fed', 'Irrigated'],
    ),
    FertilizerCrop(
      id: 'crop_tobacco',
      name: 'Tobacco',
      scientificName: 'Nicotiana tabacum',
      category: CropCategory.fieldCrop,
      iconEmoji: '🍂',
      defaultStages: ['Basal / Transplanting', 'First Top Dress (3 Weeks)', 'Second Top Dress (5-6 Weeks)', 'All Season Total'],
      supportedProductionSystems: ['Rain-fed', 'Irrigated'],
    ),
    FertilizerCrop(
      id: 'crop_sugarcane',
      name: 'Sugarcane',
      scientificName: 'Saccharum officinarum',
      category: CropCategory.fieldCrop,
      iconEmoji: '🎋',
      defaultStages: ['Planting / Ratoon Basal', 'Tillering Top Dress (60 Days)', 'Boom Growth (120 Days)', 'All Season Total'],
      supportedProductionSystems: ['Irrigated', 'Rain-fed'],
    ),
    FertilizerCrop(
      id: 'crop_cassava',
      name: 'Cassava',
      scientificName: 'Manihot esculenta',
      category: CropCategory.fieldCrop,
      iconEmoji: '🥔',
      defaultStages: ['Basal / Planting', 'Tuber Bulking (3 Months)', 'All Season Total'],
      supportedProductionSystems: ['Rain-fed'],
    ),
    FertilizerCrop(
      id: 'crop_potato',
      name: 'Irish Potato',
      scientificName: 'Solanum tuberosum',
      category: CropCategory.fieldCrop,
      iconEmoji: '🥔',
      defaultStages: ['Basal / Furrow Planting', 'Tuber Initiation & Hilling', 'Tuber Bulking', 'All Season Total'],
      supportedProductionSystems: ['Irrigated', 'Rain-fed'],
      requiresYieldTarget: true,
      defaultYieldTarget: 30.0,
      yieldUnit: 'tonnes/ha',
    ),
    FertilizerCrop(
      id: 'crop_sweet_potato',
      name: 'Sweet Potato',
      scientificName: 'Ipomoea batatas',
      category: CropCategory.fieldCrop,
      iconEmoji: '🍠',
      defaultStages: ['Basal / Ridge Planting', 'Vine Growth & Root Bulking', 'All Season Total'],
      supportedProductionSystems: ['Rain-fed', 'Irrigated'],
    ),

    // HORTICULTURAL CROPS - VEGETABLES
    FertilizerCrop(
      id: 'crop_tomato',
      name: 'Tomato',
      scientificName: 'Solanum lycopersicum',
      category: CropCategory.vegetable,
      iconEmoji: '🍅',
      defaultStages: [
        'Basal / Transplanting',
        'Early Vegetative (2-3 Weeks)',
        'First Flower Set',
        'Fruit Development & Harvest',
        'All Season Total',
      ],
      supportedProductionSystems: ['Open Field', 'Irrigated', 'Greenhouse', 'Drip Fertigation'],
      requiresYieldTarget: true,
      defaultYieldTarget: 50.0,
      yieldUnit: 'tonnes/ha',
    ),
    FertilizerCrop(
      id: 'crop_cabbage',
      name: 'Cabbage & Brassicas',
      scientificName: 'Brassica oleracea',
      category: CropCategory.vegetable,
      iconEmoji: '🥬',
      defaultStages: [
        'Basal / Transplanting',
        'First Top Dress (3 Weeks)',
        'Head Formation / Second Top Dress (6 Weeks)',
        'All Season Total',
      ],
      supportedProductionSystems: ['Open Field', 'Irrigated', 'Rain-fed'],
    ),
    FertilizerCrop(
      id: 'crop_onion',
      name: 'Onion & Garlic',
      scientificName: 'Allium cepa',
      category: CropCategory.vegetable,
      iconEmoji: '🧅',
      defaultStages: [
        'Basal / Transplanting',
        'Vegetative Top Dress (4 Weeks)',
        'Bulb Enlargement Stage',
        'All Season Total',
      ],
      supportedProductionSystems: ['Irrigated', 'Open Field'],
    ),
    FertilizerCrop(
      id: 'crop_pepper',
      name: 'Bell Pepper & Chilli',
      scientificName: 'Capsicum annuum',
      category: CropCategory.vegetable,
      iconEmoji: '🌶️',
      defaultStages: [
        'Basal / Transplanting',
        'Vegetative Growth',
        'Flowering & Continuous Fruit Set',
        'All Season Total',
      ],
      supportedProductionSystems: ['Open Field', 'Greenhouse', 'Irrigated'],
    ),
    FertilizerCrop(
      id: 'crop_carrot',
      name: 'Carrot & Root Crops',
      scientificName: 'Daucus carota',
      category: CropCategory.vegetable,
      iconEmoji: '🥕',
      defaultStages: ['Basal / Sowing', 'Root Development (4-6 Weeks)', 'All Season Total'],
      supportedProductionSystems: ['Irrigated', 'Open Field'],
    ),
    FertilizerCrop(
      id: 'crop_cucumber',
      name: 'Cucumber & Squash',
      scientificName: 'Cucumis sativus',
      category: CropCategory.vegetable,
      iconEmoji: '🥒',
      defaultStages: ['Basal / Planting', 'Vine Extension & Flowering', 'Harvest Period', 'All Season Total'],
      supportedProductionSystems: ['Open Field', 'Greenhouse', 'Irrigated'],
    ),
    FertilizerCrop(
      id: 'crop_green_beans',
      name: 'Green Beans (Snap / Fine Beans)',
      scientificName: 'Phaseolus vulgaris',
      category: CropCategory.vegetable,
      iconEmoji: '🫘',
      defaultStages: ['Basal / Planting', 'Flowering & Pod Setting', 'All Season Total'],
      supportedProductionSystems: ['Irrigated', 'Open Field', 'Greenhouse'],
    ),
    FertilizerCrop(
      id: 'crop_spinach',
      name: 'Spinach & Swiss Chard',
      scientificName: 'Spinacia oleracea',
      category: CropCategory.vegetable,
      iconEmoji: '🥬',
      defaultStages: ['Basal / Planting', 'Post-Harvest Ratoon Dressing', 'All Season Total'],
      supportedProductionSystems: ['Irrigated', 'Open Field'],
    ),
    FertilizerCrop(
      id: 'crop_watermelon',
      name: 'Watermelon & Melons',
      scientificName: 'Citrullus lanatus',
      category: CropCategory.vegetable,
      iconEmoji: '🍉',
      defaultStages: ['Basal / Planting', 'Vine Running Top Dress', 'Fruit Expansion Top Dress', 'All Season Total'],
      supportedProductionSystems: ['Irrigated', 'Open Field'],
    ),

    // FRUIT CROPS
    FertilizerCrop(
      id: 'crop_banana',
      name: 'Banana & Plantain',
      scientificName: 'Musa acuminata',
      category: CropCategory.fruit,
      iconEmoji: '🍌',
      defaultStages: [
        'Planting Hole Basal',
        'Vegetative Stool Maintenance (Every 3 Months)',
        'Flowering & Bunch Development',
        'Annual Maintenance Total',
      ],
      supportedProductionSystems: ['Irrigated', 'Rain-fed'],
    ),
    FertilizerCrop(
      id: 'crop_avocado',
      name: 'Avocado',
      scientificName: 'Persea americana',
      category: CropCategory.fruit,
      iconEmoji: '🥑',
      defaultStages: [
        'Planting Hole Establishment',
        'Post-Harvest Flush (Autumn)',
        'Pre-Bloom & Flowering (Spring)',
        'Fruit Growth (Summer)',
        'Annual Maintenance Total',
      ],
      supportedProductionSystems: ['Irrigated', 'Rain-fed'],
    ),
    FertilizerCrop(
      id: 'crop_citrus',
      name: 'Citrus (Orange, Lemon, Lime)',
      scientificName: 'Citrus spp.',
      category: CropCategory.fruit,
      iconEmoji: '🍊',
      defaultStages: [
        'Spring Vegetative Flush & Blossom',
        'Fruit Sizing (Summer)',
        'Post-Harvest Maintenance',
        'Annual Maintenance Total',
      ],
      supportedProductionSystems: ['Irrigated'],
    ),
    FertilizerCrop(
      id: 'crop_mango',
      name: 'Mango',
      scientificName: 'Mangifera indica',
      category: CropCategory.fruit,
      iconEmoji: '🥭',
      defaultStages: [
        'Post-Harvest Pruning Flush',
        'Pre-Flowering',
        'Fruit Development',
        'Annual Maintenance Total',
      ],
      supportedProductionSystems: ['Irrigated', 'Rain-fed'],
    ),

    // TREE / PERENNIAL CROPS
    FertilizerCrop(
      id: 'crop_coffee',
      name: 'Coffee (Arabica & Robusta)',
      scientificName: 'Coffea arabica',
      category: CropCategory.treeAndPerennial,
      iconEmoji: '☕',
      defaultStages: [
        'Onset of Early Rains (Pre-Bloom)',
        'Berry Expansion & Bean Filling',
        'Post-Harvest Rest & Root Regeneration',
        'Annual Total',
      ],
      supportedProductionSystems: ['Rain-fed', 'Irrigated', 'Shade-grown'],
    ),
    FertilizerCrop(
      id: 'crop_macadamia',
      name: 'Macadamia Nut',
      scientificName: 'Macadamia integrifolia',
      category: CropCategory.treeAndPerennial,
      iconEmoji: '🌰',
      defaultStages: [
        'Flowering & Nut Set (Spring)',
        'Nut Shell Hardening & Oil Accumulation',
        'Post-Harvest Flush',
        'Annual Total',
      ],
      supportedProductionSystems: ['Irrigated', 'Rain-fed'],
    ),
    FertilizerCrop(
      id: 'crop_tea',
      name: 'Tea',
      scientificName: 'Camellia sinensis',
      category: CropCategory.treeAndPerennial,
      iconEmoji: '🍵',
      defaultStages: [
        'Spring Shoot Flush Split',
        'Mid-Season Maintenance Split',
        'Late Season Split',
        'Annual Total',
      ],
      supportedProductionSystems: ['Rain-fed', 'Irrigated'],
    ),

    // HERBS & SPECIALTY
    FertilizerCrop(
      id: 'crop_basil',
      name: 'Sweet Basil & Culinary Herbs',
      scientificName: 'Ocimum basilicum',
      category: CropCategory.herbAndSpecialty,
      iconEmoji: '🌿',
      defaultStages: ['Basal / Potting Bed', 'Post-Harvest Cut Ratoon Split', 'All Season Total'],
      supportedProductionSystems: ['Greenhouse', 'Open Field', 'Hydroponic', 'Container'],
    ),
  ];

  // ---------------------------------------------------------------------------
  // 5. VERIFIED AGRONOMIC RECOMMENDATIONS (LINKED TO REAL SOURCES & MARKETS)
  // ---------------------------------------------------------------------------
  static const List<FertilizerRecommendation> recommendations = [
    // --- ZIMBABWE MAIZE (DR&SS Verified) ---
    FertilizerRecommendation(
      id: 'rec_zw_maize_basal',
      cropId: 'crop_maize',
      cropName: 'Maize (Corn)',
      stageName: 'Basal / Planting',
      countryCode: 'ZW',
      countryName: 'Zimbabwe',
      regionName: 'Natural Region II (Intensive Farming / Mashonaland)',
      productionSystem: 'Rain-fed',
      confidence: RecommendationConfidence.verified,
      nKgPerHaRec: 28.0,
      p2o5KgPerHaRec: 56.0,
      k2oKgPerHaRec: 28.0,
      sKgPerHaRec: 24.0,
      preferredProductId: 'prod_zw_compound_d',
      preferredProductName: 'Compound D (7-14-7 + 6S)',
      rateKgPerHaMin: 350.0,
      rateKgPerHaRec: 400.0,
      rateKgPerHaMax: 450.0,
      rateUnit: 'kg/ha',
      applicationMethod: 'Banded 5 cm to the side and 5 cm below the seed line at planting.',
      timingGuidance: 'Apply in furrow or planting basin before placing and covering seed.',
      agronomicTips: [
        'Never place seed in direct contact with fertilizer granules to prevent salt burn and poor germination.',
        'In sandy soils (Region IV/V), split basal application or incorporate cattle manure (5-10 t/ha) to improve CEC.',
      ],
      sourceId: 'src_drss_zim',
    ),
    FertilizerRecommendation(
      id: 'rec_zw_maize_topdress',
      cropId: 'crop_maize',
      cropName: 'Maize (Corn)',
      stageName: 'Early Vegetative (V4 - V6 / Knee High)',
      countryCode: 'ZW',
      countryName: 'Zimbabwe',
      regionName: 'Natural Region II (Intensive Farming / Mashonaland)',
      productionSystem: 'Rain-fed',
      confidence: RecommendationConfidence.verified,
      nKgPerHaRec: 103.5,
      p2o5KgPerHaRec: 0.0,
      k2oKgPerHaRec: 0.0,
      preferredProductId: 'prod_zw_an',
      preferredProductName: 'Ammonium Nitrate (34.5% N)',
      rateKgPerHaMin: 250.0,
      rateKgPerHaRec: 300.0,
      rateKgPerHaMax: 350.0,
      rateUnit: 'kg/ha',
      applicationMethod: 'Side-dressed 10-15 cm from the plant base along crop row.',
      timingGuidance: 'Apply at 4-6 weeks after emergence (knee-high / V6 stage) when soil is moist or just before rain.',
      agronomicTips: [
        'For high-yield targets (>7 t/ha) or very sandy soils, split the top dressing: 150 kg/ha at 4 weeks and 150 kg/ha at 7 weeks (tasseling).',
        'Do not apply top dressing on dry soil without impending rain or irrigation.',
      ],
      sourceId: 'src_drss_zim',
    ),
    FertilizerRecommendation(
      id: 'rec_zw_maize_full_season',
      cropId: 'crop_maize',
      cropName: 'Maize (Corn)',
      stageName: 'All Season Total',
      countryCode: 'ZW',
      countryName: 'Zimbabwe',
      productionSystem: 'Rain-fed',
      confidence: RecommendationConfidence.verified,
      nKgPerHaRec: 131.5,
      p2o5KgPerHaRec: 56.0,
      k2oKgPerHaRec: 28.0,
      sKgPerHaRec: 24.0,
      preferredProductId: 'prod_zw_compound_d',
      preferredProductName: 'Compound D + Ammonium Nitrate',
      rateKgPerHaRec: 700.0,
      rateUnit: 'kg/ha',
      applicationMethod: 'Split program: Basal at planting + Top dressing at knee-high.',
      timingGuidance: 'Apply 400 kg/ha Compound D at planting followed by 300 kg/ha AN at 5-6 weeks.',
      splitRules: [
        SplitApplicationRule(
          stageName: 'Basal / Planting',
          timing: 'At planting',
          percentageOfTotal: 57.0,
          preferredProductId: 'prod_zw_compound_d',
          preferredProductName: 'Compound D (7-14-7 + 6S)',
          applicationMethod: 'Banded 5cm beside seed',
        ),
        SplitApplicationRule(
          stageName: 'Top Dressing',
          timing: '4-6 weeks after emergence (Knee-high)',
          percentageOfTotal: 43.0,
          preferredProductId: 'prod_zw_an',
          preferredProductName: 'Ammonium Nitrate (34.5% N)',
          applicationMethod: 'Side-dress along row',
        ),
      ],
      agronomicTips: [
        'Total seasonal nutrient balance: 130 kg N, 56 kg P2O5, 28 kg K2O.',
        'Follow with lime application (500-1000 kg/ha) every 3-4 years if soil pH is below 5.2.',
      ],
      sourceId: 'src_drss_zim',
    ),

    // --- BRAZIL CERRADO MAIZE (EMBRAPA Verified) ---
    FertilizerRecommendation(
      id: 'rec_br_maize_basal',
      cropId: 'crop_maize',
      cropName: 'Maize (Corn)',
      stageName: 'Basal / Planting',
      countryCode: 'BR',
      countryName: 'Brazil',
      regionName: 'Centro-Oeste / Cerrado (Mato Grosso, Goiás, MS)',
      productionSystem: 'Rain-fed',
      confidence: RecommendationConfidence.verified,
      nKgPerHaRec: 20.0,
      p2o5KgPerHaRec: 100.0,
      k2oKgPerHaRec: 60.0,
      sKgPerHaRec: 20.0,
      preferredProductId: 'prod_br_npk_05_25_15',
      preferredProductName: 'NPK 05-25-15 (Plantio Grãos Alto Rendimento)',
      rateKgPerHaMin: 350.0,
      rateKgPerHaRec: 400.0,
      rateKgPerHaMax: 450.0,
      rateUnit: 'kg/ha',
      applicationMethod: 'No sulco de plantio, 5 cm ao lado e 5 cm abaixo da semente.',
      timingGuidance: 'Aplicado no momento da semeadura mecanizada.',
      agronomicTips: [
        'Solos de Cerrado demandam alta saturação por bases (V% 60-70%) obtida por calagem prévia.',
        'Fósforo é crítico em solos argilosos do Cerrado devido à alta fixação em óxidos de ferro/alumínio.',
      ],
      sourceId: 'src_embrapa_br',
    ),
    FertilizerRecommendation(
      id: 'rec_br_maize_topdress',
      cropId: 'crop_maize',
      cropName: 'Maize (Corn)',
      stageName: 'Early Vegetative (V4 - V6 / Knee High)',
      countryCode: 'BR',
      countryName: 'Brazil',
      regionName: 'Centro-Oeste / Cerrado (Mato Grosso, Goiás, MS)',
      productionSystem: 'Rain-fed',
      confidence: RecommendationConfidence.verified,
      nKgPerHaRec: 120.0,
      p2o5KgPerHaRec: 0.0,
      k2oKgPerHaRec: 60.0,
      preferredProductId: 'prod_br_npk_20_00_20',
      preferredProductName: 'NPK 20-00-20 (Adubo Cobertura)',
      rateKgPerHaMin: 250.0,
      rateKgPerHaRec: 300.0,
      rateKgPerHaMax: 350.0,
      rateUnit: 'kg/ha',
      applicationMethod: 'Aplicação a lanço ou em linha entre as fileiras de milho.',
      timingGuidance: 'Estádio V4 a V6 (4 a 6 folhas completamente expandidas).',
      agronomicTips: [
        'Em caso de utilizar Ureia pura, aplicar imediatamente antes de chuvas ou com solo úmido para minimizar perdas por volatilização.',
      ],
      sourceId: 'src_embrapa_br',
    ),

    // --- KENYA MAIZE (KALRO Verified) ---
    FertilizerRecommendation(
      id: 'rec_ke_maize_basal',
      cropId: 'crop_maize',
      cropName: 'Maize (Corn)',
      stageName: 'Basal / Planting',
      countryCode: 'KE',
      countryName: 'Kenya',
      regionName: 'Rift Valley (Trans-Nzoia, Uasin Gishu, Nakuru)',
      productionSystem: 'Rain-fed',
      confidence: RecommendationConfidence.verified,
      nKgPerHaRec: 25.0,
      p2o5KgPerHaRec: 65.0,
      k2oKgPerHaRec: 25.0,
      sKgPerHaRec: 10.0,
      caKgPerHaRec: 20.0,
      preferredProductId: 'prod_ke_mavuno_planting',
      preferredProductName: 'Mavuno Planting NPK (10-26-10 + Micros)',
      rateKgPerHaMin: 200.0,
      rateKgPerHaRec: 250.0,
      rateKgPerHaMax: 300.0,
      rateUnit: 'kg/ha',
      applicationMethod: 'Placement in planting hole/furrow mixed with a thin layer of soil before seed placement.',
      timingGuidance: 'Apply at onset of long rains during planting.',
      agronomicTips: [
        'Mavuno or DAP provides essential phosphate for root expansion in acidic volcanic and humic soils of Trans-Nzoia.',
        'Use 1 bottle cap (approx 5-6g) per planting hill if doing hand-planting.',
      ],
      sourceId: 'src_kalro_ke',
    ),
    FertilizerRecommendation(
      id: 'rec_ke_maize_topdress',
      cropId: 'crop_maize',
      cropName: 'Maize (Corn)',
      stageName: 'Early Vegetative (V4 - V6 / Knee High)',
      countryCode: 'KE',
      countryName: 'Kenya',
      regionName: 'Rift Valley (Trans-Nzoia, Uasin Gishu, Nakuru)',
      productionSystem: 'Rain-fed',
      confidence: RecommendationConfidence.verified,
      nKgPerHaRec: 65.0,
      p2o5KgPerHaRec: 0.0,
      k2oKgPerHaRec: 0.0,
      preferredProductId: 'prod_can_global',
      preferredProductName: 'CAN (Calcium Ammonium Nitrate 27-0-0)',
      rateKgPerHaMin: 200.0,
      rateKgPerHaRec: 250.0,
      rateKgPerHaMax: 300.0,
      rateUnit: 'kg/ha',
      applicationMethod: 'Side-dress 10 cm away from plant stem when maize is knee high.',
      timingGuidance: 'Apply 4 to 6 weeks after sowing when soil is moist.',
      agronomicTips: [
        'CAN is strongly preferred over Urea in acidic Kenyan highlands because it supplies calcium and does not acidify topsoil.',
      ],
      sourceId: 'src_kalro_ke',
    ),

    // --- SOUTH AFRICA TOMATO (ARC / Fertasa Verified) ---
    FertilizerRecommendation(
      id: 'rec_za_tomato_basal',
      cropId: 'crop_tomato',
      cropName: 'Tomato',
      stageName: 'Basal / Transplanting',
      countryCode: 'ZA',
      countryName: 'South Africa',
      regionName: 'Limpopo (Subtropical & Bushveld)',
      productionSystem: 'Irrigated',
      confidence: RecommendationConfidence.verified,
      nKgPerHaRec: 40.0,
      p2o5KgPerHaRec: 60.0,
      k2oKgPerHaRec: 80.0,
      preferredProductId: 'prod_za_2_3_4_30',
      preferredProductName: '2:3:4 (30) + 0.5% Zn (Vegetable Basal)',
      rateKgPerHaMin: 500.0,
      rateKgPerHaRec: 600.0,
      rateKgPerHaMax: 700.0,
      rateUnit: 'kg/ha',
      applicationMethod: 'Broadcast and incorporated into planting beds before laying mulch and drip lines.',
      timingGuidance: 'Incorporate 1-2 days before transplanting seedlings.',
      agronomicTips: [
        'Ensure soil calcium is adequate to prevent Blossom End Rot (BER). Maintain soil pH (KCl) above 5.8.',
        'Follow with weekly fertigation program matching nitrogen and potassium during fruit bulking.',
      ],
      sourceId: 'src_arc_za',
    ),

    // --- UNITED STATES CORN / MAIZE (Midwest / Tri-State Guide) ---
    FertilizerRecommendation(
      id: 'rec_us_maize_all_season',
      cropId: 'crop_maize',
      cropName: 'Maize (Corn)',
      stageName: 'All Season Total',
      countryCode: 'US',
      countryName: 'United States',
      regionName: 'Corn Belt / Midwest (Iowa, Illinois, Indiana, Ohio, Minnesota)',
      productionSystem: 'Rain-fed',
      confidence: RecommendationConfidence.verified,
      nKgPerHaRec: 180.0,
      p2o5KgPerHaRec: 70.0,
      k2oKgPerHaRec: 90.0,
      preferredProductId: 'prod_dap_global',
      preferredProductName: 'DAP (18-46-0) + Potash (0-0-60) + UAN 32%',
      rateKgPerHaRec: 450.0,
      rateUnit: 'kg/ha',
      applicationMethod: 'Pre-plant broadcast P & K with split pre-emergence/sidedress N application.',
      timingGuidance: 'P and K applied fall/spring; 30% N at planting and 70% N sidedressed at V6.',
      splitRules: [
        SplitApplicationRule(
          stageName: 'Pre-Plant / Starter',
          timing: 'At planting 2x2 band',
          percentageOfTotal: 35.0,
          preferredProductId: 'prod_dap_global',
          preferredProductName: 'DAP (18-46-0)',
          applicationMethod: '2x2 Starter band',
        ),
        SplitApplicationRule(
          stageName: 'Sidedress Nitrogen',
          timing: 'V6 stage (Knee high)',
          percentageOfTotal: 65.0,
          preferredProductId: 'prod_us_uan_32',
          preferredProductName: 'UAN 32% Liquid / Urea',
          applicationMethod: 'Coulter injected / side dressed',
        ),
      ],
      agronomicTips: [
        'Calculated based on 10 t/ha (160 bu/acre) grain yield goal.',
        'Credit nitrogen from previous soybean crop (30-40 kg N/ha credit).',
      ],
      sourceId: 'src_usda_extension',
    ),

    // --- INDIA WHEAT (ICAR STCR Verified) ---
    FertilizerRecommendation(
      id: 'rec_in_wheat_all_season',
      cropId: 'crop_wheat',
      cropName: 'Wheat',
      stageName: 'All Season Total',
      countryCode: 'IN',
      countryName: 'India',
      regionName: 'Indo-Gangetic Plains (Punjab, Haryana, Uttar Pradesh, Bihar)',
      productionSystem: 'Irrigated',
      confidence: RecommendationConfidence.verified,
      nKgPerHaRec: 120.0,
      p2o5KgPerHaRec: 60.0,
      k2oKgPerHaRec: 40.0,
      preferredProductId: 'prod_dap_global',
      preferredProductName: 'DAP (18-46-0) + Neem-Coated Urea + MOP',
      rateKgPerHaRec: 350.0,
      rateUnit: 'kg/ha',
      applicationMethod: 'Full P & K + 1/3 N at sowing; remaining N top dressed in 2 equal splits at CRI and late tillering.',
      timingGuidance: 'Basal at sowing; 1st top dress at 21 days (Crown Root Initiation) with 1st irrigation; 2nd top dress at 45 days.',
      agronomicTips: [
        'Neem coated urea ensures steady supply during rapid tillering.',
        'In zinc-deficient soils, apply 25 kg/ha Zinc Sulphate (21% Zn) as basal.',
      ],
      sourceId: 'src_icar_india',
    ),

    // --- GENERAL FAO INTERNATIONAL FALLBACK BENCHMARKS ---
    FertilizerRecommendation(
      id: 'rec_fao_tomato_general',
      cropId: 'crop_tomato',
      cropName: 'Tomato',
      stageName: 'Basal / Transplanting',
      countryCode: 'GLOBAL',
      countryName: 'Global',
      productionSystem: 'Any',
      confidence: RecommendationConfidence.general,
      nKgPerHaRec: 50.0,
      p2o5KgPerHaRec: 80.0,
      k2oKgPerHaRec: 80.0,
      preferredProductId: 'prod_npk_17_17_17',
      preferredProductName: 'NPK 17-17-17 Balanced Compound',
      rateKgPerHaMin: 400.0,
      rateKgPerHaRec: 470.0,
      rateKgPerHaMax: 550.0,
      rateUnit: 'kg/ha',
      applicationMethod: 'Incorporate into the root zone before transplanting seedlings.',
      timingGuidance: 'Apply 1-3 days before transplanting into moist soil bed.',
      agronomicTips: [
        'General benchmark. Soil testing recommended for accurate P and K requirements.',
      ],
      sourceId: 'src_fao_nutrition',
    ),
    FertilizerRecommendation(
      id: 'rec_fao_cabbage_general',
      cropId: 'crop_cabbage',
      cropName: 'Cabbage & Brassicas',
      stageName: 'Basal / Transplanting',
      countryCode: 'GLOBAL',
      countryName: 'Global',
      productionSystem: 'Any',
      confidence: RecommendationConfidence.general,
      nKgPerHaRec: 60.0,
      p2o5KgPerHaRec: 90.0,
      k2oKgPerHaRec: 60.0,
      preferredProductId: 'prod_npk_15_15_15',
      preferredProductName: 'NPK 15-15-15 Compound',
      rateKgPerHaMin: 450.0,
      rateKgPerHaRec: 500.0,
      rateKgPerHaMax: 600.0,
      rateUnit: 'kg/ha',
      applicationMethod: 'Incorporate into planting rows or basins.',
      timingGuidance: 'Apply at transplanting.',
      agronomicTips: [
        'Cabbage is a heavy nitrogen and potassium feeder. Top dress with straight nitrogen 3-4 weeks after transplanting.',
      ],
      sourceId: 'src_fao_nutrition',
    ),
    FertilizerRecommendation(
      id: 'rec_fao_onion_general',
      cropId: 'crop_onion',
      cropName: 'Onion & Garlic',
      stageName: 'Basal / Transplanting',
      countryCode: 'GLOBAL',
      countryName: 'Global',
      productionSystem: 'Any',
      confidence: RecommendationConfidence.general,
      nKgPerHaRec: 40.0,
      p2o5KgPerHaRec: 80.0,
      k2oKgPerHaRec: 80.0,
      preferredProductId: 'prod_npk_17_17_17',
      preferredProductName: 'NPK 17-17-17 Balanced Compound',
      rateKgPerHaMin: 400.0,
      rateKgPerHaRec: 470.0,
      rateKgPerHaMax: 500.0,
      rateUnit: 'kg/ha',
      applicationMethod: 'Broadcast and thoroughly disk or hoe into the top 15 cm of soil.',
      timingGuidance: 'Prior to transplanting sets or seedlings.',
      agronomicTips: [
        'Stop all nitrogen top dressings 3-4 weeks before bulb maturity to prevent thick necks and storage rot.',
      ],
      sourceId: 'src_fao_nutrition',
    ),
    FertilizerRecommendation(
      id: 'rec_fao_banana_general',
      cropId: 'crop_banana',
      cropName: 'Banana & Plantain',
      stageName: 'Annual Maintenance Total',
      countryCode: 'GLOBAL',
      countryName: 'Global',
      productionSystem: 'Any',
      confidence: RecommendationConfidence.general,
      nKgPerHaRec: 200.0,
      p2o5KgPerHaRec: 60.0,
      k2oKgPerHaRec: 300.0,
      preferredProductId: 'prod_npk_17_17_17',
      preferredProductName: 'NPK 17-17-17 + MOP Potash',
      rateKgPerHaMin: 800.0,
      rateKgPerHaRec: 1000.0,
      rateKgPerHaMax: 1200.0,
      rateUnit: 'kg/ha',
      applicationMethod: 'Ring application around the mat within 1-1.5m radius under canopy mulch.',
      timingGuidance: 'Split into 3 to 4 equal applications throughout the rainy/irrigation season.',
      agronomicTips: [
        'Bananas require tremendous potassium for fruit filling and bunch size.',
        'Always apply beneath thick organic mulch to preserve root surface moisture.',
      ],
      sourceId: 'src_fao_nutrition',
    ),
  ];
}
